// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbsqlite

import (
	"context"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (id, project_id, flag_id, action, actor, payload)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, project_id, flag_id, action, actor, payload, created_at
`

type AppendAuditEventParams struct {
	ID        string
	ProjectID *string
	FlagID    *string
	Action    string
	Actor     *string
	Payload   string
}

type AppendAuditEventRow struct {
	ID        string
	ProjectID *string
	FlagID    *string
	Action    string
	Actor     *string
	Payload   string
	CreatedAt string
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error) {
	row := q.db.QueryRowContext(ctx, appendAuditEvent,
		arg.ID,
		arg.ProjectID,
		arg.FlagID,
		arg.Action,
		arg.Actor,
		arg.Payload,
	)
	var i AppendAuditEventRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FlagID,
		&i.Action,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByProject = `-- name: ListAuditEventsByProject :many
SELECT id, project_id, flag_id, action, actor, payload, created_at
FROM audit_events
WHERE project_id = ?1
  AND (?2 IS NULL OR action = ?2)
  AND (?3  IS NULL OR actor  = ?3)
  AND (?4   IS NULL OR created_at >= ?4)
  AND (?5     IS NULL OR created_at <  ?5)
  AND (
        ?6 IS NULL
        OR created_at < ?6
        OR (created_at = ?6 AND id < ?7)
      )
ORDER BY created_at DESC, id DESC
LIMIT ?8
`

type ListAuditEventsByProjectParams struct {
	ProjectID *string
	Action    interface{}
	Actor     interface{}
	From      interface{}
	To        interface{}
	CursorTs  interface{}
	CursorID  *string
	Limit     int64
}

type ListAuditEventsByProjectRow struct {
	ID        string
	ProjectID *string
	FlagID    *string
	Action    string
	Actor     *string
	Payload   string
	CreatedAt string
}

func (q *Queries) ListAuditEventsByProject(ctx context.Context, arg ListAuditEventsByProjectParams) ([]ListAuditEventsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByProject,
		arg.ProjectID,
		arg.Action,
		arg.Actor,
		arg.From,
		arg.To,
		arg.CursorTs,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsByProjectRow
	for rows.Next() {
		var i ListAuditEventsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FlagID,
			&i.Action,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
