// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package dbsqlite

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, slug, name)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, slug, name, created_at
`

type CreateEnvironmentParams struct {
	ID        string
	ProjectID string
	Slug      string
	Name      string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentBySlug = `-- name: GetEnvironmentBySlug :one
SELECT id, project_id, slug, name, created_at
FROM environments
WHERE project_id = ? AND slug = ?
`

type GetEnvironmentBySlugParams struct {
	ProjectID string
	Slug      string
}

func (q *Queries) GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentBySlug, arg.ProjectID, arg.Slug)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, slug, name, created_at
FROM environments
WHERE project_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
