// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlite

type AuditEvent struct {
	ID        string
	ProjectID *string
	FlagID    *string
	Action    string
	Payload   string
	CreatedAt string
	Actor     *string
}

type Environment struct {
	ID        string
	ProjectID string
	Slug      string
	Name      string
	CreatedAt string
}

type Flag struct {
	ID           string
	ProjectID    string
	Key          string
	Name         string
	Description  string
	ValueType    string
	DefaultValue string
	CreatedAt    string
	UpdatedAt    string
}

type FlagVersion struct {
	ID          string
	FlagID      string
	Version     int64
	Strategy    string
	Source      string
	Compiled    string
	PublishedAt string
	SourceText  *string
}

type Project struct {
	ID             string
	Slug           string
	DisplayName    string
	ConfigStrategy string
	CreatedAt      string
	UpdatedAt      string
}

type Segment struct {
	ID          string
	ProjectID   string
	Key         string
	Name        string
	Description string
	Predicate   string
	CreatedAt   string
	UpdatedAt   string
}

type Snapshot struct {
	ID            string
	ProjectID     string
	EnvironmentID *string
	Version       int64
	Compiled      string
	CreatedAt     string
}
