// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlite

import (
	"context"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error)
	CreateFlagVersion(ctx context.Context, arg CreateFlagVersionParams) (FlagVersion, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error)
	GetFlagByKey(ctx context.Context, arg GetFlagByKeyParams) (Flag, error)
	GetLatestFlagVersion(ctx context.Context, flagID string) (FlagVersion, error)
	GetLatestSnapshot(ctx context.Context, projectID string) (Snapshot, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetSegmentByKey(ctx context.Context, arg GetSegmentByKeyParams) (Segment, error)
	GetSnapshotByID(ctx context.Context, arg GetSnapshotByIDParams) (Snapshot, error)
	ListAuditEventsByProject(ctx context.Context, arg ListAuditEventsByProjectParams) ([]ListAuditEventsByProjectRow, error)
	ListEnvironmentsByProject(ctx context.Context, projectID string) ([]Environment, error)
	ListFlagVersions(ctx context.Context, flagID string) ([]FlagVersion, error)
	ListFlagsByProject(ctx context.Context, projectID string) ([]Flag, error)
	ListLatestFlagVersions(ctx context.Context, projectID string) ([]ListLatestFlagVersionsRow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSegmentsByProject(ctx context.Context, projectID string) ([]Segment, error)
	ListSnapshotsByProject(ctx context.Context, arg ListSnapshotsByProjectParams) ([]Snapshot, error)
	NextFlagVersion(ctx context.Context, flagID string) (int64, error)
	NextSnapshotVersion(ctx context.Context, projectID string) (int64, error)
	UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error)
}

var _ Querier = (*Queries)(nil)
