// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package dbsqlite

import (
	"context"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (id, project_id, key, name, description, predicate)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, project_id, key, name, description, predicate, created_at, updated_at
`

type CreateSegmentParams struct {
	ID          string
	ProjectID   string
	Key         string
	Name        string
	Description string
	Predicate   string
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, createSegment,
		arg.ID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Predicate,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentByKey = `-- name: GetSegmentByKey :one
SELECT id, project_id, key, name, description, predicate, created_at, updated_at
FROM segments
WHERE project_id = ? AND key = ?
`

type GetSegmentByKeyParams struct {
	ProjectID string
	Key       string
}

func (q *Queries) GetSegmentByKey(ctx context.Context, arg GetSegmentByKeyParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, getSegmentByKey, arg.ProjectID, arg.Key)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSegmentsByProject = `-- name: ListSegmentsByProject :many
SELECT id, project_id, key, name, description, predicate, created_at, updated_at
FROM segments
WHERE project_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSegmentsByProject(ctx context.Context, projectID string) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Predicate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegment = `-- name: UpdateSegment :one
UPDATE segments
SET name        = ?1,
    description = ?2,
    predicate   = ?3,
    updated_at  = ?4
WHERE project_id = ?5 AND key = ?6
RETURNING id, project_id, key, name, description, predicate, created_at, updated_at
`

type UpdateSegmentParams struct {
	Name        string
	Description string
	Predicate   string
	UpdatedAt   string
	ProjectID   string
	Key         string
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, updateSegment,
		arg.Name,
		arg.Description,
		arg.Predicate,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.Key,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
