// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package dbsqlite

import (
	"context"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (id, project_id, environment_id, version, compiled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, environment_id, version, compiled, created_at
`

type CreateSnapshotParams struct {
	ID            string
	ProjectID     string
	EnvironmentID *string
	Version       int64
	Compiled      string
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Version,
		arg.Compiled,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = ?
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, projectID string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, projectID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = ? AND id = ?
`

type GetSnapshotByIDParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetSnapshotByID(ctx context.Context, arg GetSnapshotByIDParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByID, arg.ProjectID, arg.ID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestFlagVersions = `-- name: ListLatestFlagVersions :many
SELECT
    flag_key,
    flag_id,
    version,
    strategy,
    compiled,
    published_at
FROM (
    SELECT
        f.key            AS flag_key,
        fv.flag_id       AS flag_id,
        fv.version       AS version,
        fv.strategy      AS strategy,
        fv.compiled      AS compiled,
        fv.published_at  AS published_at,
        ROW_NUMBER() OVER (PARTITION BY fv.flag_id ORDER BY fv.version DESC) AS rn
    FROM flag_versions fv
    INNER JOIN flags f ON f.id = fv.flag_id
    WHERE f.project_id = ?
)
WHERE rn = 1
`

type ListLatestFlagVersionsRow struct {
	FlagKey     string
	FlagID      string
	Version     int64
	Strategy    string
	Compiled    string
	PublishedAt string
}

func (q *Queries) ListLatestFlagVersions(ctx context.Context, projectID string) ([]ListLatestFlagVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestFlagVersions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestFlagVersionsRow
	for rows.Next() {
		var i ListLatestFlagVersionsRow
		if err := rows.Scan(
			&i.FlagKey,
			&i.FlagID,
			&i.Version,
			&i.Strategy,
			&i.Compiled,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByProject = `-- name: ListSnapshotsByProject :many
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = ?
ORDER BY version DESC
LIMIT ?
`

type ListSnapshotsByProjectParams struct {
	ProjectID string
	Limit     int64
}

func (q *Queries) ListSnapshotsByProject(ctx context.Context, arg ListSnapshotsByProjectParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Version,
			&i.Compiled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSnapshotVersion = `-- name: NextSnapshotVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM snapshots
WHERE project_id = ?
`

func (q *Queries) NextSnapshotVersion(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSnapshotVersion, projectID)
	var next_version int64
	err := row.Scan(&next_version)
	return next_version, err
}
