{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falseflag.operatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falseflag.componentLabels" (dict "root" . "component" "operator") | nindent 4 }}
{{- end }}
