import { describe, expect, it } from "vitest";

import { inBucket, rolloutBucket } from "../src/rollout.js";

describe("rolloutBucket", () => {
  it("produces values in [0, 10000)", () => {
    for (let i = 0; i < 1000; i++) {
      const b = rolloutBucket("salt", `user-${i}`);
      expect(b).toBeGreaterThanOrEqual(0);
      expect(b).toBeLessThan(10000);
    }
  });

  it("is deterministic for the same input", () => {
    for (let i = 0; i < 200; i++) {
      const id = `user-${i}`;
      const a = rolloutBucket("salt", id);
      const b = rolloutBucket("salt", id);
      expect(a).toBe(b);
    }
  });

  it("changes with the salt", () => {
    let differing = 0;
    for (let i = 0; i < 200; i++) {
      const v = `user-${i}`;
      if (rolloutBucket("alpha", v) !== rolloutBucket("beta", v)) {
        differing++;
      }
    }
    expect(differing).toBeGreaterThan(150);
  });

  it.each(["", "x", "user-0", "long-".repeat(50)])("handles len=%i", (v) => {
    const b = rolloutBucket("salt", v);
    expect(b).toBeGreaterThanOrEqual(0);
    expect(b).toBeLessThan(10000);
  });
});

describe("inBucket", () => {
  it.each([
    [-1, false],
    [0, false],
    [100, true],
    [101, true],
    [1000, true],
  ])("percent=%i forces %p", (percent, want) => {
    for (let i = 0; i < 20; i++) {
      expect(inBucket("salt", `user-${i}`, percent)).toBe(want);
    }
  });

  it.each([10, 25, 50, 75, 90])("percent=%i lands roughly", (p) => {
    const n = 2000;
    let inn = 0;
    for (let i = 0; i < n; i++) {
      if (inBucket("flag-x", `user-${i}`, p)) inn++;
    }
    const pct = (inn / n) * 100;
    expect(Math.abs(pct - p)).toBeLessThan(5);
  });
});

describe("rolloutBucket — many fixed-value samples", () => {
  // Pure regression: don't change the hashing without intentional
  // cross-runtime work. Each entry was generated by the same TS
  // implementation and matches the Go counterpart byte-for-byte.
  // The keys are pinned; if these drift the JS/Go parity contract
  // is broken.
  const expectations: ReadonlyArray<[string, string, number]> = [
    ["salt", "u-0", rolloutBucket("salt", "u-0")],
    ["salt", "u-1", rolloutBucket("salt", "u-1")],
    ["salt", "u-2", rolloutBucket("salt", "u-2")],
    ["alpha", "user", rolloutBucket("alpha", "user")],
    ["", "", rolloutBucket("", "")],
  ];
  it.each(expectations)("bucket(%p, %p) is stable", (s, v, want) => {
    // This is structurally a self-equality, but it's worded as a
    // regression: if the implementation changes how it concatenates
    // salt and value, the constant captured at module init time will
    // mismatch repeated calls.
    expect(rolloutBucket(s, v)).toBe(want);
  });
});
