// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (id, project_id, flag_id, action, actor, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, flag_id, action, actor, payload, created_at
`

type AppendAuditEventParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FlagID    pgtype.UUID
	Action    string
	Actor     pgtype.Text
	Payload   []byte
}

type AppendAuditEventRow struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FlagID    pgtype.UUID
	Action    string
	Actor     pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppendAuditEventRow, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.ID,
		arg.ProjectID,
		arg.FlagID,
		arg.Action,
		arg.Actor,
		arg.Payload,
	)
	var i AppendAuditEventRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FlagID,
		&i.Action,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByProject = `-- name: ListAuditEventsByProject :many
SELECT id, project_id, flag_id, action, actor, payload, created_at
FROM audit_events
WHERE project_id = $1
  AND ($3::text IS NULL OR action = $3::text)
  AND ($4::text  IS NULL OR actor  = $4::text)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz   IS NULL OR created_at <  $6::timestamptz)
  AND (
        $7::timestamptz IS NULL
        OR (created_at, id) < ($7::timestamptz, $8::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditEventsByProjectParams struct {
	ProjectID pgtype.UUID
	Limit     int32
	Action    pgtype.Text
	Actor     pgtype.Text
	From      pgtype.Timestamptz
	To        pgtype.Timestamptz
	CursorTs  pgtype.Timestamptz
	CursorID  pgtype.UUID
}

type ListAuditEventsByProjectRow struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FlagID    pgtype.UUID
	Action    string
	Actor     pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAuditEventsByProject(ctx context.Context, arg ListAuditEventsByProjectParams) ([]ListAuditEventsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByProject,
		arg.ProjectID,
		arg.Limit,
		arg.Action,
		arg.Actor,
		arg.From,
		arg.To,
		arg.CursorTs,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsByProjectRow
	for rows.Next() {
		var i ListAuditEventsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FlagID,
			&i.Action,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
