// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (id, project_id, key, name, description, value_type, default_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, key, name, description, value_type, default_value, created_at, updated_at
`

type CreateFlagParams struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Key          string
	Name         string
	Description  string
	ValueType    string
	DefaultValue []byte
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, createFlag,
		arg.ID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.ValueType,
		arg.DefaultValue,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlagVersion = `-- name: CreateFlagVersion :one
INSERT INTO flag_versions (id, flag_id, version, strategy, source, compiled, source_text)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, flag_id, version, strategy, source, compiled, published_at, source_text
`

type CreateFlagVersionParams struct {
	ID         pgtype.UUID
	FlagID     pgtype.UUID
	Version    int32
	Strategy   string
	Source     []byte
	Compiled   []byte
	SourceText pgtype.Text
}

func (q *Queries) CreateFlagVersion(ctx context.Context, arg CreateFlagVersionParams) (FlagVersion, error) {
	row := q.db.QueryRow(ctx, createFlagVersion,
		arg.ID,
		arg.FlagID,
		arg.Version,
		arg.Strategy,
		arg.Source,
		arg.Compiled,
		arg.SourceText,
	)
	var i FlagVersion
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Version,
		&i.Strategy,
		&i.Source,
		&i.Compiled,
		&i.PublishedAt,
		&i.SourceText,
	)
	return i, err
}

const getFlagByKey = `-- name: GetFlagByKey :one
SELECT id, project_id, key, name, description, value_type, default_value, created_at, updated_at
FROM flags
WHERE project_id = $1 AND key = $2
`

type GetFlagByKeyParams struct {
	ProjectID pgtype.UUID
	Key       string
}

func (q *Queries) GetFlagByKey(ctx context.Context, arg GetFlagByKeyParams) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlagByKey, arg.ProjectID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ValueType,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestFlagVersion = `-- name: GetLatestFlagVersion :one
SELECT id, flag_id, version, strategy, source, compiled, published_at, source_text
FROM flag_versions
WHERE flag_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestFlagVersion(ctx context.Context, flagID pgtype.UUID) (FlagVersion, error) {
	row := q.db.QueryRow(ctx, getLatestFlagVersion, flagID)
	var i FlagVersion
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Version,
		&i.Strategy,
		&i.Source,
		&i.Compiled,
		&i.PublishedAt,
		&i.SourceText,
	)
	return i, err
}

const listFlagVersions = `-- name: ListFlagVersions :many
SELECT id, flag_id, version, strategy, source, compiled, published_at, source_text
FROM flag_versions
WHERE flag_id = $1
ORDER BY version DESC
`

func (q *Queries) ListFlagVersions(ctx context.Context, flagID pgtype.UUID) ([]FlagVersion, error) {
	rows, err := q.db.Query(ctx, listFlagVersions, flagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagVersion
	for rows.Next() {
		var i FlagVersion
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.Version,
			&i.Strategy,
			&i.Source,
			&i.Compiled,
			&i.PublishedAt,
			&i.SourceText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlagsByProject = `-- name: ListFlagsByProject :many
SELECT id, project_id, key, name, description, value_type, default_value, created_at, updated_at
FROM flags
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFlagsByProject(ctx context.Context, projectID pgtype.UUID) ([]Flag, error) {
	rows, err := q.db.Query(ctx, listFlagsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.ValueType,
			&i.DefaultValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFlagVersion = `-- name: NextFlagVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM flag_versions
WHERE flag_id = $1
`

func (q *Queries) NextFlagVersion(ctx context.Context, flagID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFlagVersion, flagID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}
