// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FlagID    pgtype.UUID
	Action    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	Actor     pgtype.Text
}

type Environment struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Flag struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Key          string
	Name         string
	Description  string
	ValueType    string
	DefaultValue []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type FlagVersion struct {
	ID          pgtype.UUID
	FlagID      pgtype.UUID
	Version     int32
	Strategy    string
	Source      []byte
	Compiled    []byte
	PublishedAt pgtype.Timestamptz
	SourceText  pgtype.Text
}

type Project struct {
	ID             pgtype.UUID
	Slug           string
	DisplayName    string
	ConfigStrategy string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Segment struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Key         string
	Name        string
	Description string
	Predicate   []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Snapshot struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	EnvironmentID pgtype.UUID
	Version       int32
	Compiled      []byte
	CreatedAt     pgtype.Timestamptz
}
