// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (id, project_id, key, name, description, predicate)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, key, name, description, predicate, created_at, updated_at
`

type CreateSegmentParams struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Key         string
	Name        string
	Description string
	Predicate   []byte
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment,
		arg.ID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Predicate,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentByKey = `-- name: GetSegmentByKey :one
SELECT id, project_id, key, name, description, predicate, created_at, updated_at
FROM segments
WHERE project_id = $1 AND key = $2
`

type GetSegmentByKeyParams struct {
	ProjectID pgtype.UUID
	Key       string
}

func (q *Queries) GetSegmentByKey(ctx context.Context, arg GetSegmentByKeyParams) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegmentByKey, arg.ProjectID, arg.Key)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSegmentsByProject = `-- name: ListSegmentsByProject :many
SELECT id, project_id, key, name, description, predicate, created_at, updated_at
FROM segments
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSegmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Predicate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegment = `-- name: UpdateSegment :one
UPDATE segments
SET name        = $3,
    description = $4,
    predicate   = $5,
    updated_at  = $6
WHERE project_id = $1 AND key = $2
RETURNING id, project_id, key, name, description, predicate, created_at, updated_at
`

type UpdateSegmentParams struct {
	ProjectID   pgtype.UUID
	Key         string
	Name        string
	Description string
	Predicate   []byte
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, updateSegment,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Predicate,
		arg.UpdatedAt,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
