// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (id, project_id, environment_id, version, compiled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, environment_id, version, compiled, created_at
`

type CreateSnapshotParams struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	EnvironmentID pgtype.UUID
	Version       int32
	Compiled      []byte
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Version,
		arg.Compiled,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, projectID pgtype.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, projectID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = $1 AND id = $2
`

type GetSnapshotByIDParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) GetSnapshotByID(ctx context.Context, arg GetSnapshotByIDParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByID, arg.ProjectID, arg.ID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Version,
		&i.Compiled,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestFlagVersions = `-- name: ListLatestFlagVersions :many
SELECT DISTINCT ON (fv.flag_id)
    f.key            AS flag_key,
    fv.flag_id       AS flag_id,
    fv.version       AS version,
    fv.strategy      AS strategy,
    fv.compiled      AS compiled,
    fv.published_at  AS published_at
FROM flag_versions fv
INNER JOIN flags f ON f.id = fv.flag_id
WHERE f.project_id = $1
ORDER BY fv.flag_id, fv.version DESC
`

type ListLatestFlagVersionsRow struct {
	FlagKey     string
	FlagID      pgtype.UUID
	Version     int32
	Strategy    string
	Compiled    []byte
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) ListLatestFlagVersions(ctx context.Context, projectID pgtype.UUID) ([]ListLatestFlagVersionsRow, error) {
	rows, err := q.db.Query(ctx, listLatestFlagVersions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestFlagVersionsRow
	for rows.Next() {
		var i ListLatestFlagVersionsRow
		if err := rows.Scan(
			&i.FlagKey,
			&i.FlagID,
			&i.Version,
			&i.Strategy,
			&i.Compiled,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByProject = `-- name: ListSnapshotsByProject :many
SELECT id, project_id, environment_id, version, compiled, created_at
FROM snapshots
WHERE project_id = $1
ORDER BY version DESC
LIMIT $2
`

type ListSnapshotsByProjectParams struct {
	ProjectID pgtype.UUID
	Limit     int32
}

func (q *Queries) ListSnapshotsByProject(ctx context.Context, arg ListSnapshotsByProjectParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Version,
			&i.Compiled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSnapshotVersion = `-- name: NextSnapshotVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM snapshots
WHERE project_id = $1
`

func (q *Queries) NextSnapshotVersion(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSnapshotVersion, projectID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}
