name: ci-build

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  build-images:
    name: build-images
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      - uses: depot/bake-action@v1
